// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfcKVinlMfqyXhYBTix5eB2G08Bg1UZJo',
    appId: '1:605027692464:android:9092ec1c5bbc219faf7075',
    messagingSenderId: '605027692464',
    projectId: 'cs310-a5fba',
    storageBucket: 'cs310-a5fba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr_NRVO5bxfAvbFls0q3STlfyTWNelUCA',
    appId: '1:605027692464:ios:c53193286f48e2b8af7075',
    messagingSenderId: '605027692464',
    projectId: 'cs310-a5fba',
    storageBucket: 'cs310-a5fba.firebasestorage.app',
    iosBundleId: 'com.example.navigateScreens',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBucEHY2op59H4KHBpcSzNdwYHlDg9k2DE',
    appId: '1:605027692464:web:bf34a5320e42e1eaaf7075',
    messagingSenderId: '605027692464',
    projectId: 'cs310-a5fba',
    authDomain: 'cs310-a5fba.firebaseapp.com',
    storageBucket: 'cs310-a5fba.firebasestorage.app',
    measurementId: 'G-VT7KX7XQH1',
  );

}